### ISSUE TITLE
Add Options -Indexes in .htaccess

### ISSUE THREAD

**Issue by HashtagAssist** [sunshinephotocart/sunshine-photo-cart#1]
It should, in my opinion, actually be standard that "Options -Indexes" is in the htaccess in the main directory. However, I noticed that in the /wp-uploads folder, in the directory for "Sunshine" is a htaccess and this also contains no "Options -Indexes" setting.

**Comment by sunshinephotocart** [comment]
I do not put Sunshine on Github anymore, this is incredibly old cold. I am actually going to remove this repo right now.

Thanks for the feedback though!
